// constants/languages.js
// Complete list of languages supported by Google Cloud Translate API
// Reference: https://cloud.google.com/translate/docs/languages

export const ALL_LANGUAGES = [
  // Top 30 most spoken languages (already in dropdown)
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'zh-CN', name: '中文 (简体)', flag: '🇨🇳' },
  { code: 'zh-TW', name: '中文 (繁體)', flag: '🇹🇼' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'jv', name: 'Basa Jawa', flag: '🇮🇩' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'ur', name: 'اردو', flag: '🇵🇰' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭' },
  { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'uk', name: 'Українська', flag: '🇺🇦' },
  { code: 'fa', name: 'فارسی', flag: '🇮🇷' },
  { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ro', name: 'Română', flag: '🇷🇴' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  
  // Additional popular languages
  { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
  { code: 'sq', name: 'Shqip', flag: '🇦🇱' },
  { code: 'am', name: 'አማርኛ', flag: '🇪🇹' },
  { code: 'hy', name: 'Հայերեն', flag: '🇦🇲' },
  { code: 'az', name: 'Azərbaycan', flag: '🇦🇿' },
  { code: 'eu', name: 'Euskara', flag: '🇪🇸' },
  { code: 'be', name: 'Беларуская', flag: '🇧🇾' },
  { code: 'bs', name: 'Bosanski', flag: '🇧🇦' },
  { code: 'bg', name: 'Български', flag: '🇧🇬' },
  { code: 'ca', name: 'Català', flag: '🇪🇸' },
  { code: 'ceb', name: 'Cebuano', flag: '🇵🇭' },
  { code: 'ny', name: 'Chichewa', flag: '🇲🇼' },
  { code: 'co', name: 'Corsu', flag: '🇫🇷' },
  { code: 'hr', name: 'Hrvatski', flag: '🇭🇷' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰' },
  { code: 'eo', name: 'Esperanto', flag: '🌍' },
  { code: 'et', name: 'Eesti', flag: '🇪🇪' },
  { code: 'tl', name: 'Filipino', flag: '🇵🇭' },
  { code: 'fi', name: 'Suomi', flag: '🇫🇮' },
  { code: 'fy', name: 'Frysk', flag: '🇳🇱' },
  { code: 'gl', name: 'Galego', flag: '🇪🇸' },
  { code: 'ka', name: 'ქართული', flag: '🇬🇪' },
  { code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'ht', name: 'Kreyòl Ayisyen', flag: '🇭🇹' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
  { code: 'haw', name: 'ʻŌlelo Hawaiʻi', flag: '🇺🇸' },
  { code: 'iw', name: 'עברית', flag: '🇮🇱' },
  { code: 'hmn', name: 'Hmong', flag: '🇱🇦' },
  { code: 'hu', name: 'Magyar', flag: '🇭🇺' },
  { code: 'is', name: 'Íslenska', flag: '🇮🇸' },
  { code: 'ig', name: 'Igbo', flag: '🇳🇬' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ga', name: 'Gaeilge', flag: '🇮🇪' },
  { code: 'kk', name: 'Қазақ', flag: '🇰🇿' },
  { code: 'km', name: 'ខ្មែរ', flag: '🇰🇭' },
  { code: 'rw', name: 'Kinyarwanda', flag: '🇷🇼' },
  { code: 'ku', name: 'Kurdî', flag: '🇮🇶' },
  { code: 'ky', name: 'Кыргызча', flag: '🇰🇬' },
  { code: 'lo', name: 'ລາວ', flag: '🇱🇦' },
  { code: 'la', name: 'Latina', flag: '🏛️' },
  { code: 'lv', name: 'Latviešu', flag: '🇱🇻' },
  { code: 'lt', name: 'Lietuvių', flag: '🇱🇹' },
  { code: 'lb', name: 'Lëtzebuergesch', flag: '🇱🇺' },
  { code: 'mk', name: 'Македонски', flag: '🇲🇰' },
  { code: 'mg', name: 'Malagasy', flag: '🇲🇬' },
  { code: 'ms', name: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'mt', name: 'Malti', flag: '🇲🇹' },
  { code: 'mi', name: 'Māori', flag: '🇳🇿' },
  { code: 'mn', name: 'Монгол', flag: '🇲🇳' },
  { code: 'my', name: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'ne', name: 'नेपाली', flag: '🇳🇵' },
  { code: 'no', name: 'Norsk', flag: '🇳🇴' },
  { code: 'or', name: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'ps', name: 'پښتو', flag: '🇦🇫' },
  { code: 'sd', name: 'سنڌي', flag: '🇵🇰' },
  { code: 'si', name: 'සිංහල', flag: '🇱🇰' },
  { code: 'sk', name: 'Slovenčina', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovenščina', flag: '🇸🇮' },
  { code: 'so', name: 'Soomaali', flag: '🇸🇴' },
  { code: 'st', name: 'Sesotho', flag: '🇱🇸' },
  { code: 'su', name: 'Basa Sunda', flag: '🇮🇩' },
  { code: 'sw', name: 'Kiswahili', flag: '🇰🇪' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'tg', name: 'Тоҷикӣ', flag: '🇹🇯' },
  { code: 'tk', name: 'Türkmen', flag: '🇹🇲' },
  { code: 'uz', name: 'Oʻzbek', flag: '🇺🇿' },
  { code: 'cy', name: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'xh', name: 'isiXhosa', flag: '🇿🇦' },
  { code: 'yi', name: 'ייִדיש', flag: '🕍' },
  { code: 'yo', name: 'Yorùbá', flag: '🇳🇬' },
  { code: 'zu', name: 'isiZulu', flag: '🇿🇦' },
];

// Export the top 30 for the dropdown (current implementation)
export const POPULAR_LANGUAGES = ALL_LANGUAGES.slice(0, 31);

// You can uncomment this to show ALL languages in dropdown:
// export { ALL_LANGUAGES as POPULAR_LANGUAGES };
